# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

matrix:
  include:
    - python: 2.7
    - python: 2.7
      env: LINT=true
    - python: 3.2
    - python: 3.3
    - python: 3.4
      env: NOSE_WITH_COVERAGE=y NOSE_COVER_PACKAGE=siphon
    - python: 3.4
      env: LINT=true

notifications:
  email: false

before_install:
  - if [[ $LINT == true ]]; then
      pip install flake8 pep8-naming;
    else
      pip install -r requirements.txt;
      pip install vcrpy;
      if [[ $NOSE_WITH_COVERAGE == y ]]; then
        pip install coverage;
      fi;
    fi

install:
  - python setup.py install

script:
  - if [[ $LINT == true ]]; then
      flake8 siphon;
    else
      nosetests;
    fi

after_success:
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      pip install coveralls;
      coveralls;
    fi
