# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

env: PEP8=false

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.4
      env: PEP8=true

notifications:
  email: false

before_install:
  - if [[ $PEP8 == true ]]; then
      pip install pep8;
    fi

#install:
  #- python setup.py install

script:
  - if [[ $PEP8 == true ]]; then
      pep8 pyudl;
    else
      nosetests;
    fi
