# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env: LINT=false
    - python: 3.3
      env: LINT=false
    - python: 3.4
      env: LINT=false
    - python: 3.4
      env: LINT=true

notifications:
  email: false

before_install:
  - if [[ $LINT == true ]]; then
      pip install flake8;
    fi

install:
  - python setup.py install

script:
  - if [[ $LINT == true ]]; then
      flake8 pyudl;
    else
      nosetests;
    fi
