# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

addons:
  artifacts:
    target_paths: /
    paths:
      - $(find $WHEELDIR -newer $WHEELDIR/download_marker -name *.whl | tr [:space:] :)
  apt:
    packages: &base_build
    - libhdf5-serial-dev
    - libnetcdf-dev

python:
  - 3.5
  - 2.7

env:
  global:
    - secure: "mFy/PJrAVKh9Uje1+R8cEOjY8/MDj/qqjn0+FqXCTZPmBMu7RLxTfASMB8QcHfDrJDhH3lEUqkt/uAbGsOKsDIWn/pjKqm6qyvsdw2ISoARommD5lOL3A3Q/Mti1Hz1u4J8CKa0zaGj88NmIyJ2zC8ZyrCl6qS6bTNv7E6A1AIs="
    - WHEELHOUSE="https://unidata-python.s3.amazonaws.com/wheelhouse/index.html"
    - WHEELDIR="wheelhouse/"
    - EXTRAS="test"
  matrix:
    - TASK="coverage"
    - TASK="examples"
    - TASK="lint"

matrix:
  include:
    - python: 2.7
      env: TASK="docs"
      addons:
        apt:
          packages:
            - *base_build
            - pandoc
    - python: 3.3
      env:
    - python: 3.4
      env:
    - python: "3.5-dev"
      env: PRE="--pre"
    - python: nightly
      env: PRE="--pre"
  allow_failures:
    - python: "3.5-dev"
    - python: nightly

before_install:
  - if [[ $TASK == "lint" ]]; then
      pip install flake8 pep8-naming;
    else
      pip install --upgrade pip;
      if [[ $TASK == "docs" || $TASK == "examples" ]]; then
        if [[ $TASK == "examples" ]]; then
          export EXTRAS="$EXTRAS,examples";
        fi;
        pip install -r docs/requirements.txt;
      elif [[ $TASK == "coverage" ]]; then
        pip install pytest-cov;
      fi;
      mkdir $WHEELDIR;
      pip install ".[$EXTRAS]" -d $WHEELDIR -f $WHEELHOUSE $PRE $VERSIONS;
      touch $WHEELDIR/download_marker;
      travis_wait pip wheel ".[$EXTRAS]" -w $WHEELDIR -f $WHEELHOUSE $PRE $VERSIONS;
      rm -f $WHEELDIR/siphon*.whl;
    fi

install:
  - if [[ $TASK != "lint" && $TASK != "docs" ]]; then
      pip install ".[$EXTRAS]" --upgrade --no-index -f file://$PWD/$WHEELDIR $VERSIONS;
      if [[ $TASK == "examples" ]]; then
        python setup.py examples;
      fi;
    fi

script:
  - if [[ $TASK == "lint" ]]; then
      flake8 siphon;
    elif [[ $TASK == "docs" ]]; then
      cd docs;
      make html;
    elif [[ $TASK == "examples" ]]; then
      cd examples;
      echo backend:agg > matplotlibrc;
      MPLBACKEND='agg' python test_examples.py;
    elif [[ $TASK == "coverage" ]]; then
      python setup.py test --addopts --cov=siphon;
    else
      python setup.py test;
    fi

after_success:
  - if [[ $TASK == "coverage" ]]; then
      pip install codecov codacy-coverage;
      codecov;
      coverage xml;
      python-codacy-coverage -r coverage.xml;
    fi
