# Create full conda environment for development, including some useful tools
name: devel
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3
  - requests
  - protobuf
  - netcdf4
  - jupyter
  - sphinx
  - pytest
  - pytest-cov
  - vcrpy
  - flake8
  - pep8-naming
  - matplotlib
  - xarray
